import { Radley } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import RightSidebar from "./components/RightSidebar";
import LeftSidebar from "./components/LeftSidebar";

const radley = Radley({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={radley.className}>
        <Navbar />
        <LeftSidebar />
        {children}

        <RightSidebar />
        <Footer />
      </body>
    </html>
  );
}
